version: '3'

services:
  osis:
    ports:
      - "8000:8000"
    volumes:
      - ./osis:/app

    build: ./osis/

    env_file:
      - ./osis/.env

    depends_on:
      - db-osis
      - rabbit
      - redis

  osis-portal:
    volumes:
      - ./osis-portal/:/app
    ports:
      - "8001:8000"
    build: ./osis-portal/

    env_file:
      - ./osis-portal/.env

    depends_on:
      - db-osis-portal
      - rabbit
      - redis

  db-osis:
    image: postgres:9.6
    restart: always
    env_file:
      - ./osis/.env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

  db-osis-portal:
    image: postgres:9.6
    restart: always
    env_file:
      - ./osis-portal/.env
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata-portal:/var/lib/postgresql/data/

  rabbit:
    image: rabbitmq

  redis:
    image: redis
